version: '3.3'

services:  
  sql:
    container_name: hub-sql
    image: bitnami/postgresql:latest
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - ./data/sql:/bitnami
    environment:
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_USERNAME: cobi
      POSTGRESQL_DATABASE: cobi-data
  redis:
    container_name: hub-redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data/redis:/bitnami
    environment:
      REDIS_PASSWORD: redis-xyz
  rabbitmq:
    container_name: hub-rabbitmq
    image: bitnami/rabbitmq:latest
    restart: always
    volumes:
      - ./data/rabbitmq:/bitnami
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    environment:
      RABBITMQ_PASSWORD: cobi-pass
      RABBITMQ_USERNAME: cobi
  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - ./data/mongodb:/bitnami
    ports:
      - 27017:27017
    environment:
      MONGODB_USERNAME: cobi
      MONGODB_PASSWORD: cobi-pass
      MONGODB_DATABASE: cobi_data